version: '3.8'

services:
  identity-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Trungnam@12345
    ports:
      - "1433:1433"
    volumes:
      - identity_sqldata:/var/opt/mssql

  student-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Trungnam@12345
    ports:
      - "1434:1433"
    volumes:
      - student_sqldata:/var/opt/mssql

  course-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Trungnam@12345
    ports:
      - "1435:1433"
    volumes:
      - course_sqldata:/var/opt/mssql

  identity-service:
    build:
      context: .
      dockerfile: IdentityService/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=identity-db;Database=IdentityDb;User Id=sa;Password=Trungnam@12345;TrustServerCertificate=True;
    ports:
      - "5001:8080"
    depends_on:
      - identity-db

  student-service:
    build:
      context: .
      dockerfile: StudentService/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=student-db;Database=StudentDb;User Id=sa;Password=Trungnam@12345;TrustServerCertificate=True;
    ports:
      - "5002:8080"
      - "8081:8081" # gRPC
    depends_on:
      - student-db

  course-service:
    build:
      context: .
      dockerfile: CourseService/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - Grpc__StudentService=http://student-service:8081
      - ConnectionStrings__DefaultConnection=Server=course-db;Database=CourseDb;User Id=sa;Password=Trungnam@12345;TrustServerCertificate=True;
    ports:
      - "5003:8080"
    depends_on:
      - course-db
      - student-service

  api-gateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "5000:8080"
    depends_on:
      - identity-service
      - student-service
      - course-service

volumes:
  identity_sqldata:
  student_sqldata:
  course_sqldata:
